### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by yachtsman60** [logstash-plugins/logstash-output-webhdfs#9]
The Usage section states you supply the following configuration.
"webhdfs {
    server => "127.0.0.1:50070"         # (required)
    path => "/user/logstash/dt=%{+YYYY-MM-dd}/logstash-%{+HH}.log"  # (required)
    user => "hue"                       # (required)
  }"
But the synopsis states that you supply the following configuration.
"webhdfs {
    host => ...
    path => ...
    user => ...
}"
I believe "host" is correct and "server" is incorrect and should be changed to read "host".

**Comment by markwalkom** [comment]
Good catch, care to make a PR? :D

The link to the doc is https://www.elastic.co/guide/en/logstash/current/plugins-outputs-webhdfs.html

**Comment by yachtsman60** [comment]
Done, I think. I am new to GitHub so hope what I have done is correct.

**Comment by yachtsman60** [comment]
It also already looks to be correct in this file.

https://github.com/logstash-plugins/logstash-output-webhdfs/edit/master/lib/logstash/outputs/webhdfs.rb

**Comment by dstore-dbap** [comment]
@yachtsman60 Thanks for taking the time and filing a pull request! As you already wrote, the doc error was fixed in commit 8e86cf0. Still need to check why the docs at https://www.elastic.co/guide/en/logstash/current/plugins-outputs-webhdfs.html are incorrect.

**Comment by dstore-dbap** [comment]
@markwalkom Am I right in supposing that the docs get automagically created from the doc section of the source file? Or do I need to update some other file as well?

**Comment by camypaj** [comment]
Hi @dstore-dbap, I can confirm that the problem is still there in live documentation (I learned the "hard" way). Additionally, I would remove the port from the example, because when I tried including the port, the plugin ended up connecting to "hostname:50070:50070" :)

**Comment by dstore-dbap** [comment]
@purbon Hi Pere! Do you have any idea or hint as to what will trigger an update of the current documentation at https://www.elastic.co/guide/en/logstash/current/plugins-outputs-webhdfs.html?
Just had another issue with a user getting confused with the difference between online doc and current code.

Any help would be absolutley great ;)

**Comment by dedemorton** [comment]
The docs in current have the correct options now, so I'm closing this.
